"""Generate archive/move_catalog.md — every available emotion + dance.

Pulls the actual installed libraries (not docs), so the catalog reflects
exactly what the robot can play. First run downloads ~20 MB of recorded
emotion data from Hugging Face (cached after).

Run from anywhere — paths are anchored to the project root.
"""
import os
import sys
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

ROOT = Path(__file__).resolve().parent.parent

# Read HF token from file and inject as env var. Never echo the value.
token_path = ROOT / "hf_token.txt"
if not token_path.exists():
    sys.exit(f"missing HF token at {token_path}")
token = token_path.read_text(encoding="utf-8").strip()
if not token:
    sys.exit(f"empty HF token at {token_path}")
os.environ["HF_TOKEN"] = token
os.environ["HUGGING_FACE_HUB_TOKEN"] = token

# Imports come AFTER env vars are set so huggingface_hub picks them up.
from reachy_mini.motion.recorded_move import RecordedMoves
from reachy_mini_dances_library.collection.dance import AVAILABLE_MOVES

# --- Emotions ------------------------------------------------------- #
print("Loading emotions from pollen-robotics/reachy-mini-emotions-library …")
EMOTIONS = RecordedMoves("pollen-robotics/reachy-mini-emotions-library")
emotion_pairs: list[tuple[str, str]] = []
for name in EMOTIONS.list_moves():
    try:
        desc = EMOTIONS.get(name).description or ""
    except Exception as e:
        desc = f"(could not load description: {e})"
    emotion_pairs.append((name, desc))
print(f"  → {len(emotion_pairs)} emotions")

# --- Dances --------------------------------------------------------- #
print("Loading dances from reachy_mini_dances_library …")
dance_pairs: list[tuple[str, str]] = []
for move_name, value in AVAILABLE_MOVES.items():
    # AVAILABLE_MOVES values: (func, params, metadata) tuples
    metadata = value[2] if len(value) >= 3 else {}
    desc = metadata.get("description", "") if isinstance(metadata, dict) else ""
    dance_pairs.append((move_name, desc))
print(f"  → {len(dance_pairs)} dances")

# --- Markdown ------------------------------------------------------- #
out = ROOT / "archive" / "move_catalog.md"
out.parent.mkdir(parents=True, exist_ok=True)
with out.open("w", encoding="utf-8") as f:
    f.write("# Reachy Mini move catalog\n\n")
    f.write(
        "Generated by `tools/list_moves.py` directly from the installed "
        "libraries. Re-run to refresh after a library upgrade.\n\n"
    )

    f.write(f"## Emotions ({len(emotion_pairs)})\n\n")
    f.write("Source: `pollen-robotics/reachy-mini-emotions-library` "
            "(loaded via `RecordedMoves`).\n\n")
    for n, d in sorted(emotion_pairs):
        f.write(f"- **{n}**: {d}\n")
    f.write("\n")

    f.write(f"## Dances ({len(dance_pairs)})\n\n")
    f.write("Source: `reachy_mini_dances_library.collection.dance.AVAILABLE_MOVES`.\n\n")
    for n, d in sorted(dance_pairs):
        f.write(f"- **{n}**: {d}\n")

print(f"\nWrote {out}")
print(f"  Emotions: {len(emotion_pairs)}")
print(f"  Dances:   {len(dance_pairs)}")
